export const SEO_CONFIG = {
  siteName: "TravelPepp",
  siteUrl: "https://travelpepp.com",
  defaultTitle: "TravelPepp | Premium Luxury Travel Packages — Domestic & International",
  defaultDescription: "Experience extraordinary journeys with TravelPepp. Luxury travel packages across India — Kashmir, Leh Ladakh, Himachal Pradesh, Kerala, Rajasthan, Goa, Andaman — and international destinations including Malaysia, Singapore, Thailand, Vietnam, Bali, Maldives & Kazakhstan. Bespoke itineraries, verified stays, and 24/7 concierge support.",
  facebookPage: "https://www.facebook.com/travelpepp/",
  instagramProfile: "https://www.instagram.com/travelpepp/",
  contact: {
    phone: "+91 85470 69562",
    email: "travelpepp@gmail.com",
    address: "India",
  },
  domesticDestinations: [
    "Delhi & Agra",
    "Lakshadweep",
    "Kashmir",
    "Himachal Pradesh",
    "Meghalaya",
    "Rajasthan",
    "Uttarakhand",
    "Punjab",
    "Goa",
    "Hyderabad",
    "Sikkim",
    "Maharashtra",
    "Leh Ladakh",
    "Andaman and Nicobar Islands",
    "Uttar Pradesh",
    "Sonamarg",
    "Kerala",
  ],
  internationalDestinations: [
    "Malaysia",
    "Singapore",
    "Thailand",
    "Vietnam",
    "Bali",
    "Maldives",
    "Kazakhstan",
  ],
};
